[package]
name = "ghoul"
version = "0.1.0"
authors = ["Bryan E. Barnhart <bryan.e.barnhart@gmail.com>"]

[dependencies]
blorb = { git = "https://github.com/thefarwind/blorb-rs.git" }
glulx = { git = "https://github.com/thefarwind/glulx-rs.git" }
